language: node_js
node_js:
  - "10.0.0"
git:
  depth: 1
services:
  - docker
script: npm run ci
before_deploy:
  - docker build -t jarpi/martian-robots-codetest .  
deploy:
  provider: script
  script: bash docker_push